// This file was automatically generated by go generate; DO NOT EDIT
package msg

// This file contains specialed Decode and Encode functions
// to avoid the use of the reflect package while encoding.
// In principal, everything should work when commenting out
// this file.

import "github.com/kuleuven/nfs4go/xdr"

func (x *Auth) Decode(decoder *xdr.Decoder) error {
	return decoder.DecodeAll(&x.Flavor, &x.Body)
}
	
func (x Auth) Encode(encoder *xdr.Encoder) error {
	return encoder.EncodeAll(x.Flavor, x.Body)
}

func (x *RPCMsgCall) Decode(decoder *xdr.Decoder) error {
	return decoder.DecodeAll(&x.Xid, &x.MsgType, &x.RPCVer, &x.Prog, &x.Vers, &x.Proc, &x.Cred, &x.Verf)
}
	
func (x RPCMsgCall) Encode(encoder *xdr.Encoder) error {
	return encoder.EncodeAll(x.Xid, x.MsgType, x.RPCVer, x.Prog, x.Vers, x.Proc, x.Cred, x.Verf)
}

func (x *RPCMsgReply) Decode(decoder *xdr.Decoder) error {
	return decoder.DecodeAll(&x.Xid, &x.MsgType, &x.ReplyStat)
}
	
func (x RPCMsgReply) Encode(encoder *xdr.Encoder) error {
	return encoder.EncodeAll(x.Xid, x.MsgType, x.ReplyStat)
}

func (x *RejectReply) Decode(decoder *xdr.Decoder) error {
	return decoder.DecodeAll(&x.RejectStat, &x.Lo, &x.Hi)
}
	
func (x RejectReply) Encode(encoder *xdr.Encoder) error {
	return encoder.EncodeAll(x.RejectStat, x.Lo, x.Hi)
}